version: '3.4'

services: 
    app:
        build: .
        restart: always
        ports:
            - '3000:3000'
        depends_on: 
            - db
        networks: 
            - backend
        command: ["./wait-for-it.sh", "db:5432", "--", "pm2-runtime", "start", "./server.js"]

    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - '5432:5432'
        networks: 
            - backend
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
volumes:
    pgdata:
    
networks: 
    backend:
