version: '3.4'

services: 
    docker-app:
        build: .
        restart: always
        ports:
            - '3000:3000'
        depends_on: 
            - docker-db
        networks: 
            - backend
        links:
            - docker-db
            
    docker-db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes: 
            - ./pgdata:/var/lib/postgresql/data/pgdata
        ports:
            - '5432:5432'
        networks: 
            - backend
            
networks: 
    backend:
        driver: bridge